// Login
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const GET_MY_PRODUCT_REQUEST = "GET_MY_PRODUCT_REQUEST";
export const GET_MY_PRODUCT_ERROR = "GET_MY_PRODUCT_ERROR";
export const GET_MY_PRODUCT_SUCCESS = "GET_MY_PRODUCT_SUCCESS";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

// export const LOGIN_REQUEST = "LOGIN_REQUEST";
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
// export const LOGIN_ERROR = "LOGIN_ERROR";

// export const REGISTER_REQUEST = "REGISTER_REQUEST";
// export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
// export const REGISTER_ERROR = "REGISTER_ERROR";
