import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'semantic-ui-react'

import Header from '@/component/Header'
import HeroSection from '@/component/HeroSection'
import { useSelector } from 'react-redux'

export default function Home() {
  // const getWebUser = useSelector((state) => state.WebUserReducer);
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        
        <HeroSection heading={"Home page"} />       
      </main>
    </>
  )
}
